# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FIFAapp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(390, 500))
        MainWindow.setMaximumSize(QtCore.QSize(390, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 397, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(387, 430))
        self.tableWidget.setMaximumSize(QtCore.QSize(387, 430))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(193, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(193, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(193, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(193, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 26))
        self.menubar.setObjectName("menubar")
        self.menuDownload = QtWidgets.QMenu(self.menubar)
        self.menuDownload.setObjectName("menuDownload")
        MainWindow.setMenuBar(self.menubar)
        self.actionLatest_Fixtures = QtWidgets.QAction(MainWindow)
        self.actionLatest_Fixtures.setObjectName("actionLatest_Fixtures")
        self.actionFIFA_International_Window = QtWidgets.QAction(MainWindow)
        self.actionFIFA_International_Window.setObjectName("actionFIFA_International_Window")
        self.actionUpcoming_Fixtures = QtWidgets.QAction(MainWindow)
        self.actionUpcoming_Fixtures.setObjectName("actionUpcoming_Fixtures")
        self.actionCurrent_FIFA_Rankings = QtWidgets.QAction(MainWindow)
        self.actionCurrent_FIFA_Rankings.setObjectName("actionCurrent_FIFA_Rankings")
        self.menuDownload.addAction(self.actionLatest_Fixtures)
        self.menuDownload.addAction(self.actionFIFA_International_Window)
        self.menuDownload.addAction(self.actionUpcoming_Fixtures)
        self.menuDownload.addAction(self.actionCurrent_FIFA_Rankings)
        self.menubar.addAction(self.menuDownload.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Team Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Team Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Points"))
        self.pushButton.setText(_translate("MainWindow", "Update Rankings"))
        self.pushButton_2.setText(_translate("MainWindow", "New Button"))
        self.menuDownload.setTitle(_translate("MainWindow", "Download"))
        self.actionLatest_Fixtures.setText(_translate("MainWindow", "Latest Fixtures"))
        self.actionFIFA_International_Window.setText(_translate("MainWindow", "FIFA International Window"))
        self.actionUpcoming_Fixtures.setText(_translate("MainWindow", "Upcoming Fixtures"))
        self.actionCurrent_FIFA_Rankings.setText(_translate("MainWindow", "Current FIFA Rankings"))